/*
API Data...
*/
let apps = {
  Applications: {
    "0": {
      Id: 1,
      DisplayIndex: 0,
      HeaderName: "HR Management",
      DisplayName: "HR Homepage",
      ShortName: "hrms",
      HomePageUrl: "/",
      PostInvitationUrl: "/",
      PostPasswordResetUrl: "/",
    },
    "1": {
      Id: 2,
      DisplayIndex: 1,
      HeaderName: "HR Management",
      DisplayName: "Time & Attendance",
      ShortName: "tna",
      HomePageUrl: "/",
      PostInvitationUrl: "/",
      PostPasswordResetUrl: "/",
    },
    "2": {
      Id: 3,
      DisplayIndex: 2,
      HeaderName: "Recruiting",
      DisplayName: "Applicant Tracking",
      ShortName: "tms_tracking",
      HomePageUrl: "/",
      PostInvitationUrl: "/Profile?apptest=tms_tracking",
      PostPasswordResetUrl: "/",
    },
    "3": {
      Id: 4,
      DisplayIndex: 3,
      HeaderName: "Recruiting",
      DisplayName: "Onboarding",
      ShortName: "tms_onboarding",
      HomePageUrl: "/",
      PostInvitationUrl: "/Profile?apptest=tms_onboarding",
      PostPasswordResetUrl: "/",
    },
    "4": {
      Id: 5,
      DisplayIndex: 4,
      HeaderName: "Talent Development",
      DisplayName: "Learning Management",
      ShortName: "tms_learning",
      HomePageUrl: "/MyTraining.aspx",
      PostInvitationUrl: "/Profile?apptest=tms_learning",
      PostPasswordResetUrl: "/",
    },
    "5": {
      Id: 6,
      DisplayIndex: 5,
      HeaderName: "Talent Development",
      DisplayName: "Performance",
      ShortName: "tms_performance",
      HomePageUrl: "/Evaluations/Default.aspx",
      PostInvitationUrl: "/Profile?apptest=tms_performance",
      PostPasswordResetUrl: "/",
    },
    "6": {
      Id: 7,
      DisplayIndex: 6,
      HeaderName: "Talent Development",
      DisplayName: "360 Evaluations",
      ShortName: "tms_evaluations",
      HomePageUrl: "/360Evaluations/Default.aspx",
      PostInvitationUrl: "/Profile?apptest=tms_evaluations",
      PostPasswordResetUrl: "/",
    },
    "7": {
      Id: 8,
      DisplayIndex: 7,
      HeaderName: "Talent Development",
      DisplayName: "Succession",
      ShortName: "tms_succession",
      HomePageUrl: "/SuccessionPlanning/SuccessionDashboard.aspx",
      PostInvitationUrl: "/Profile?apptest=tms_succession",
      PostPasswordResetUrl: "/",
    },
    "8": {
      Id: 9,
      DisplayIndex: 8,
      HeaderName: "Talent Development",
      DisplayName: "Knowledge Base",
      ShortName: "tms_kb",
      HomePageUrl: "/KnowledgeBase/Home",
      PostInvitationUrl: "/Profile?apptest=tms_kb",
      PostPasswordResetUrl: "/",
    },
    "9": {
      Id: 10,
      DisplayIndex: 9,
      HeaderName: "Talent Development",
      DisplayName: "Collaboration",
      ShortName: "tms_collaboration",
      HomePageUrl: "/Collaboration/Home",
      PostInvitationUrl: "/Profile?apptest=tms_collaboration",
      PostPasswordResetUrl: "/",
    },
    "10": {
      Id: 11,
      DisplayIndex: 10,
      HeaderName: "Talent Development",
      DisplayName: "Talent Dashboard",
      ShortName: "tms_dashboard",
      HomePageUrl: "/",
      PostInvitationUrl: "/Profile?apptest=tms_dashboard",
      PostPasswordResetUrl: "/",
    },
  },
};
export default apps;
